name: "Cleanup Merged Branches"
description: "Safely remove local branches that are deleted from remote and clean submodules."
author: "Gaurav Mishra"

inputs:
  pr_number:
    description: "PR number which would require pruning"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Ensure Script is Executable"
      run: |
        chmod +x ./scripts/delete_removed_branches.sh
      working-directory: .github/actions/clean-up
      shell: bash

    - name: "Remove dead branches"
      run: ./scripts/delete_removed_branches.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ inputs.pr_number }}
      working-directory: .github/actions/clean-up
      shell: bash

branding:
  icon: "trash"
  color: "red"
