name: "Cleanup Merged Branches"
description: "Safely remove local branches that are deleted from remote and clean submodules."
author: "Gaurav Mishra"

inputs:
  repo_path:
    description: "Path to the main repository"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: "Ensure Script is Executable"
      run: |
        chmod +x ./scripts/delete_removed_branches.sh
      working-directory: .github/actions/clean-up
      shell: bash

    - name: "Remove dead branches"
      run: ./scripts/delete_removed_branches.sh ${{ inputs.repo_path }}
      working-directory: .github/actions/clean-up
      shell: bash

    - name: Delete merged branch
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME=$(gh pr view ${{ inputs.pr_number }} --json headRefName --jq .headRefName)
        git push origin --delete $BRANCH_NAME

branding:
  icon: "trash"
  color: "red"
