name: "Cleanup Merged Branches"
description: "Safely remove local branches that are deleted from remote and clean submodules."
author: "Gaurav Mishra"

inputs:
  pr_number:
    description: "PR number which would require pruning"
    required: false
  is_full_cleanup:
    description: "Whether to perform full repository cleanup"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Set cleanup mode"
      id: setup
      run: |
        echo "CLEANUP_MODE=${{ inputs.is_full_cleanup == 'true' && 'full' || 'selective' }}" >> $GITHUB_ENV
      shell: bash

    - name: "Ensure Script is Executable"
      run: |
        chmod +x ./scripts/delete_removed_branches.sh
      working-directory: .github/actions/clean-up
      shell: bash

    - name: "Remove dead branches"
      run: ./scripts/delete_removed_branches.sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ inputs.pr_number }}
        CLEANUP_MODE: ${{ env.CLEANUP_MODE }}
      working-directory: .github/actions/clean-up
      shell: bash

branding:
  icon: "trash"
  color: "red"
