name: "Cleanup Merged Branches"
description: "Safely remove local branches that are deleted from remote and clean submodules."
author: "Gaurav Mishra"

inputs:
  pr_number:
    description: "PR number which would require pruning or 'full-cleanup' for full mode"
    required: false
    default: ""
  is_full_cleanup:
    description: "Whether to perform full repository cleanup"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: "Set cleanup mode"
      id: setup
      run: |
        if [[ "${{ inputs.pr_number }}" == "full-cleanup" || "${{ inputs.is_full_cleanup }}" == "true" ]]; then
          echo "CLEANUP_MODE=full" >> $GITHUB_ENV
        else
          echo "CLEANUP_MODE=selective" >> $GITHUB_ENV
        fi
      shell: bash

    - name: "Remove dead branches"
      run: |
        chmod +x ./scripts/delete_removed_branches.sh
        ./scripts/delete_removed_branches.sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
        CLEANUP_MODE: ${{ env.CLEANUP_MODE }}
      working-directory: .github/actions/clean-up
      shell: bash

branding:
  icon: "trash"
  color: "red"
