name: "Setup Python and Poetry"
description: "Set up Python environment and install Poetry"
author: "Gaurav Mishra"

inputs:
  python-versions:
    description: "Comma-separated list of Python versions to install"
    required: false
  python-version:
    description: "Python version to install"
    required: false
  specific-module:
    description: "Any specific module that has to be built"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Ensure Scripts are Executable
      run: |
        chmod +x ./.github/actions/setup-python-poetry/scripts/install_poetry.sh
        chmod +x ./.github/actions/setup-python-poetry/scripts/install_python.sh
        chmod +x ./.github/actions/setup-python-poetry/scripts/extract_python_versions.sh
      shell: bash

    - name: Extract Python Versions
      if: inputs.python-version == ''
      run: ./.github/actions/setup-python-poetry/scripts/extract_python_versions.sh "${{ inputs['python-versions'] }}"
      shell: bash

    - name: Install Python
      run: ./.github/actions/setup-python-poetry/scripts/install_python.sh "${{ inputs['python-version'] || inputs['python-versions'] || steps.extract_python_versions.outputs.python-versions }}"
      shell: bash

    - name: Install Poetry
      run: ./.github/actions/setup-python-poetry/scripts/install_poetry.sh
      shell: bash

    - name: Install Poetry Dependency
      run: poetry install ${{ inputs['specific-module'] }}
      shell: bash
