name: "Setup Python and Poetry"
description: "Set up Python environment and install Poetry"
author: "Gaurav Mishra"

inputs:
  python-versions:
    description: "Comma-separated list of Python versions to try"
    default: "3.10,3.12,3.11"
    required: false

  specific-module:
    description: "Any specific module that has to be built"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Ensure Script is Executable
      run: chmod +x ./.github/actions/setup-python-poetry/scripts/install_poetry.sh
      shell: bash

    - name: Install Python
      run: ./.github/actions/setup-python-poetry/scripts/install_python.sh "${{ inputs['python-versions'] }}"
      shell: bash

    - name: Install Poetry
      run: ./.github/actions/setup-python-poetry/scripts/install_poetry.sh
      shell: bash

    - name: Install Poetry Dependency
      run: poetry install ${{ inputs['specific-module'] }}
      shell: bash
