name: "Setup Python and Poetry"
description: "Set up Python environment and install Poetry"
author: "Gaurav Mishra"
runs:
  using: "bash"
  main: "scripts/install_poetry.sh"
inputs:
  python-version:
    description: "Python version to install"
    default: "3.x"
    required: false
