name: "Setup Python and Poetry"
description: "Set up Python environment and install Poetry"
author: "Gaurav Mishra"

inputs:
  python-version:
    description: "Python version to install"
    default: "3.10"
    required: false

  specific-module:
    description: "Any Specific module that has to be built"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Ensure Script is Executable
      run: chmod +x ./.github/actions/setup-python-poetry/scripts/install_poetry.sh
      shell: bash

    - name: Install Python and Poetry
      run: ./.github/actions/setup-python-poetry/scripts/install_poetry.sh ${{ inputs['python-version'] }}
      shell: bash

    - name: Install Poetry Dependency
      run: poetry install ${{ inputs['specific-module'] }}
      shell: bash
