services:
  default:
    build:
      context: ../../.devcontainer
      dockerfile: dockerfile
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ../../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
      - type: volume
        source: workspace-config
        target: /mnt/workspace-config
        volume:
          nocopy: true
    ports:
      - "3001:3000"  # Forward React app port
      - "5433:5432"  # Forward PostgreSQL port
      - "27018:27017" # Forward MongoDB port
      - "9093:9092"  # Forward Kafka port
      - "2182:2181"  # Forward Zookeeper port
      - "3003:3000"  # Forward Grafana port
      - "9001:9000"  # Forward SonarQube port
      - "6380:6379"  # Forward Redis port
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  grafana:
    container_name: grafana
    ports:
      - '3003:3000'

  zookeeper:
    container_name: zookeeper_devcontainer
    ports:
      - "2182:2181"

  kafka:
    container_name: kafka_devcontainer
    ports:
      - "9093:9092"

  postgres:
    container_name: postgres_devcontainer
    ports:
      - "5433:5432"

  mongodb:
    container_name: mongo_devcontainer
    ports:
      - "27018:27017"

  react:
    container_name: react_devcontainer
    ports:
      - "3001:3000"

  sonarqube:
    container_name: qube_devcontainer
    ports:
      - "9001:9000"

  redis:
    container_name: redis_devcontainer
    ports:
      - '6380:6379'

volumes:
  workspace-config:
    driver: local
