# Base image with Python
FROM mcr.microsoft.com/vscode/devcontainers/python:3.11

# Switch to root user to install prerequisites
USER root

# Install necessary tools
RUN apt-get update && \
    apt-get install -y \
    curl \
    gnupg \
    lsb-release \
    docker.io \
    nodejs \
    npm \
    default-jdk && \
    apt-get clean;

# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH=$JAVA_HOME/bin:$PATH

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> /root/.bashrc;

# Set Poetry in PATH
ENV PATH="/root/.local/bin:${PATH}"

# Set work directory
WORKDIR /workspace

# Debug: List files in the context directory
RUN echo "Listing files in context directory:" && ls -al /workspace

# Copy the pyproject.toml file into the container
COPY ../pyproject.toml /workspace/

# Debug: Verify the presence of pyproject.toml
RUN echo "Verifying pyproject.toml:" && ls -al /workspace/ && cat /workspace/pyproject.toml

# Install Python dependencies using Poetry
RUN poetry install

# Create user baseshiftcore
RUN useradd -ms /bin/bash baseshiftcore && \
    echo "baseshiftcore ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to the non-root user
USER baseshiftcore

# Add the user to the Docker group
RUN getent group docker || groupadd -g 998 docker && sudo usermod -aG docker baseshiftcore

# Default command to keep the container running (can be overridden in docker-compose)
CMD ["/bin/sh", "-c", "while sleep 1000; do :; done"]
