# Base image with Python
FROM mcr.microsoft.com/vscode/devcontainers/python:3.11

# Install necessary tools as root
USER root

# Install prerequisites
RUN apt-get update && \
    apt-get install -y \
    curl \
    gnupg \
    lsb-release \
    docker.io \
    nodejs \
    npm

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# Add Poetry to PATH
ENV PATH="/root/.local/bin:${PATH}"

# Set work directory
WORKDIR /workspace

# Debug: List files in the current directory
RUN echo "Listing files in context directory:"
RUN ls -al /workspace

# Copy the pyproject.toml file into the container
COPY ../pyproject.toml /workspace/

# Debug: Verify the presence of pyproject.toml
RUN echo "Verifying pyproject.toml:" && ls -al /workspace/ && cat /workspace/pyproject.toml

# Install Python dependencies using Poetry
RUN poetry install

# Create user baseshiftcore
RUN useradd -ms /bin/bash baseshiftcore && \
    echo "baseshiftcore ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to the non-root user
USER baseshiftcore

RUN git config --global --add safe.directory /workspace

# Add the user to the Docker group
RUN getent group docker || groupadd -g 998 docker && sudo usermod -aG docker baseshiftcore

# Default command to keep the container running (can be overridden in docker-compose)
CMD ["/bin/sh", "-c", "while sleep 1000; do :; done"]
