apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "artifactory.fullname" . }}-pvc
  labels:
    {{- include "artifactory.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | first }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
