apiVersion: v1
kind: Service
metadata:
  name: {{ include "artifactory.fullname" . }}
  labels:
    {{- include "artifactory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "artifactory.selectorLabels" . | nindent 4 }}
