replicaCount: 1

image:
  repository: jfrog/artifactory-oss
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

persistence:
  enabled: true
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 50Gi

postgresql:
  enabled: true
  postgresqlUsername: artifactory
  postgresqlPassword: artifactorypassword
  postgresqlDatabase: artifactory

resources: {}
