name: "Handle Git Submodules"
description: "Fetch, sync, and update Git submodules"
author: "Gaurav Mishra"

inputs:
  branch:
    description: "Branch to checkout in the submodules"
    default: "main"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Checkout the repo"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive  # Ensure submodules are fetched
        token: ${{ secrets.PAT_TOKEN }}  # Use your PAT token

    - name: "Handle loading submodules"
      run: ./scripts/handle_submodules.sh ${{ inputs.branch }}
      working-directory: .github/actions/handle-submodules
      shell: bash
