name: "Handle Git Submodules"
description: "Fetch, sync, and update Git submodules"
author: "Gaurav Mishra"

inputs:
  branch:
    description: "Branch to checkout in the submodules"
    default: "main"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Handle loading submodules"
      run: ./scripts/handle_submodules.sh ${{ inputs.branch }}
      working-directory: .github/actions/handle-submodules
      shell: bash
