name: 🧹 Post PR Clean-up

on:
  pull_request:
    types: [closed]

  workflow_dispatch:

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository with submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive  # Ensure submodules are fetched
          token: ${{ secrets.PAT_TOKEN }}  # Use your PAT token

      # Use the custom action to handle submodules
      - name: Handle Git Submodules
        uses: ./.github/actions/handle-submodules
        with:
          branch: 'main'

      - name: Run Clean-up scripts
        uses: ./.github/actions/clean-up
        with:
          repo_path: '.'
