name: 🧹 Post PR Clean-up

on:
  pull_request:
    types: [closed]

  workflow_dispatch:

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo with submodules
        uses: ./.github/actions/handle-submodules

      - name: Run Clean-up scripts
        uses: ./.github/actions/clean-up
        with:
          branch: 'main'
          repo_path: ''
