name: 🧹 Post PR Clean-up

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Ensures submodules are fetched

      - name: Run Clean-up scripts
        run: |
          bash .github/actions/cleanup/run_cleanup.sh
